wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 32
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_epochs:
  value: 10
num_hidden_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_initialization:
  value: random
