wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_epochs:
  value: 10
num_hidden_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_initialization:
  value: xavier
