wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 16
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_epochs:
  value: 10
num_hidden_layers:
  value: 4
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_initialization:
  value: xavier
