wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_epochs:
  value: 5
num_hidden_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_initialization:
  value: random
